### ISSUE TITLE
Updated Mythos Entities

### ISSUE THREAD

**Issue by Vogliadicone** [stories-with-dice/delta-green-open-mythos#1]
I updated all open mythos creatures and made also simple tokens for them. And since I didn't know, how to best do a merge request, I created with FVTT a module with a actor compendium in it. I uploaded it in a [ZIP-File to my Google Drive](https://drive.google.com/file/d/10tD8bLKI0vOvyQKaIg0n98GUC4Issuj6/view?usp=sharing) (let me know, when you have downloaded it so I can put it down). Included is a folder icons with all the (old and) new images. The new images have to be copied into the icons folder of your module. Let me know, if that works for you or if there is a better / easier way to update this module.

I created the compendium with FVTT 12.330 and DG 1.4.7.

Since DG has now two new item types (rituals & tomes), I'm planning on creating next all the rituals and equip the creatures with them. When I'm finished with that, I could send you the updated compendiums.

**Comment by Vogliadicone** [comment]
I think, I managed to update my fork. So in theory I could also do a pull request. If you prefer.

**Comment by stories-with-dice** [comment]
Thank you for your contribution! Could you please open a PR?

**Comment by Vogliadicone** [comment]
Will do. But since I'm in holidays, I won't be able to do this before august 25/26.

**Comment by Vogliadicone** [comment]
I opened a PR.

**Comment by Vogliadicone** [comment]
Updated creatures in v0.3

**Comment by Vogliadicone** [comment]
Updated creatures in v0.3
